/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.josefeyjoo.almacen.view;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author jfeyj
 */
public class Formulario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario.class.getName());

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        codigoText = new javax.swing.JTextField();
        nifnText = new javax.swing.JTextField();
        nombreText = new javax.swing.JTextField();
        apellidosText = new javax.swing.JTextField();
        domicilioText = new javax.swing.JTextField();
        cpText = new javax.swing.JTextField();
        localidadText = new javax.swing.JTextField();
        telefonoText = new javax.swing.JTextField();
        movilText = new javax.swing.JTextField();
        faxText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        totalText = new javax.swing.JTextField();
        niflText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prueba de entrada de datos");

        codigoText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                codigoTextCaretUpdate(evt);
            }
        });
        codigoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextActionPerformed(evt);
            }
        });

        nifnText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nifnTextCaretUpdate(evt);
            }
        });
        nifnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nifnTextActionPerformed(evt);
            }
        });

        nombreText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nombreTextCaretUpdate(evt);
            }
        });
        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });

        apellidosText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                apellidosTextCaretUpdate(evt);
            }
        });
        apellidosText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosTextActionPerformed(evt);
            }
        });

        domicilioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domicilioTextActionPerformed(evt);
            }
        });

        cpText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                cpTextCaretUpdate(evt);
            }
        });
        cpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpTextActionPerformed(evt);
            }
        });

        localidadText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                localidadTextCaretUpdate(evt);
            }
        });
        localidadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidadTextActionPerformed(evt);
            }
        });

        telefonoText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                telefonoTextCaretUpdate(evt);
            }
        });
        telefonoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTextActionPerformed(evt);
            }
        });

        movilText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                movilTextCaretUpdate(evt);
            }
        });
        movilText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movilTextActionPerformed(evt);
            }
        });

        faxText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                faxTextCaretUpdate(evt);
            }
        });
        faxText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxTextActionPerformed(evt);
            }
        });

        emailText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                emailTextCaretUpdate(evt);
            }
        });
        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });

        totalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTextActionPerformed(evt);
            }
        });

        niflText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                niflTextCaretUpdate(evt);
            }
        });
        niflText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                niflTextFocusLost(evt);
            }
        });
        niflText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niflTextActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("N.I.F");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellidos");

        jLabel5.setText("Domicilio");

        jLabel6.setText("Codigo Postal");

        jLabel7.setText("Localidad");

        jLabel8.setText("Teléfono");

        jLabel9.setText("Móvil");

        jLabel10.setText("Fax");

        jLabel11.setText("Email");

        jLabel12.setText("Total Ventas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nifnText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(niflText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(domicilioText, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidosText, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(localidadText, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movilText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(faxText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jLabel12)))
                    .addComponent(jLabel11))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nifnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(niflText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(apellidosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(domicilioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localidadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movilText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codigoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextActionPerformed

    }//GEN-LAST:event_codigoTextActionPerformed

    private void nifnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nifnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nifnTextActionPerformed

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextActionPerformed

    private void apellidosTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosTextActionPerformed

    private void domicilioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domicilioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domicilioTextActionPerformed

    private void cpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpTextActionPerformed

    private void localidadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidadTextActionPerformed

    private void telefonoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTextActionPerformed

    private void movilTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movilTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movilTextActionPerformed

    private void faxTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faxTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faxTextActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void totalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTextActionPerformed

    private void niflTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niflTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niflTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String text = "Errores en: \n";
               
        ArrayList<String> errores = new ArrayList<>();
        if (!(codigoCheck(codigoText.getText()))){
            errores.add("Código");
        }
        if (!(numCheck(nifnText.getText()))){
            errores.add("DNI");
        }
        
        if (!comprobarDNI()){
            errores.add("Letra del DNI");
        }
        if (!(nameCheck(nombreText.getText()))) {
            errores.add("Nombre");
        }
        if (!(nameCheck(apellidosText.getText()))) {
            errores.add("Apellidos");
        }
        if (domicilioText.getText().isEmpty()){
            errores.add("Domicilio");
        }
        if (!(cpCheck(cpText.getText()))) {
            errores.add("C.P.");
        }
        if (!(phoneCheck(telefonoText.getText()))) {
            errores.add("Teléfono");
        }
        if (!(phoneCheck(movilText.getText()))) {
            errores.add("Móvil");
        }
        if (!(phoneCheck(faxText.getText()))) {
            errores.add("Fax");
        }
        if (!(emailCheck(emailText.getText()))) {
            errores.add("email");
        }
        
        
        
        if (errores.size()==1){
            text = "Error en: ";
        }
        
        for (int i = 0; i < errores.size(); i++){
            if (i == errores.size()-1){
                text += errores.get(i);
            } else {
                text += errores.get(i) + ", ";
            }
        }
        
        
        if (errores.isEmpty()) {
            jOptionPane1.showMessageDialog(null, "Formulario Finalizado con Éxito", "Formulario Finalizado", jOptionPane1.INFORMATION_MESSAGE);
        } else {
            jOptionPane1.showMessageDialog(null, text, "Ventana Error", jOptionPane1.YES_OPTION);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codigoTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_codigoTextCaretUpdate
        String text = codigoText.getText();
        if (codigoCheck(text)){
            codigoText.setForeground(Color.BLACK);
        } else {
            codigoText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_codigoTextCaretUpdate

    private void nifnTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nifnTextCaretUpdate
        String text = nifnText.getText();
        if (numCheck(text)){
            nifnText.setForeground(Color.BLACK);
        } else {
            nifnText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_nifnTextCaretUpdate

    private void nombreTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nombreTextCaretUpdate
        String text = nombreText.getText();
        if (nameCheck(text)){
            nombreText.setForeground(Color.BLACK);
        } else {
            nombreText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_nombreTextCaretUpdate

    private void apellidosTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_apellidosTextCaretUpdate
        String text = apellidosText.getText();
        if (nameCheck(text)){
            apellidosText.setForeground(Color.BLACK);
        } else {
            apellidosText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_apellidosTextCaretUpdate

    private void cpTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_cpTextCaretUpdate
        String text = cpText.getText();
        if (cpCheck(text)){
            cpText.setForeground(Color.BLACK);
        } else {
            cpText.setForeground(Color.RED);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cpTextCaretUpdate

    private void telefonoTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_telefonoTextCaretUpdate
        String text = telefonoText.getText();
        if (phoneCheck(text)){
            telefonoText.setForeground(Color.BLACK);
        } else {
            telefonoText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_telefonoTextCaretUpdate

    private void movilTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_movilTextCaretUpdate
        String text = movilText.getText();
        if (phoneCheck(text)){
            movilText.setForeground(Color.BLACK);
        } else {
            movilText.setForeground(Color.RED);
        } 
    }//GEN-LAST:event_movilTextCaretUpdate

    private void faxTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_faxTextCaretUpdate
        String text = faxText.getText();
        if (phoneCheck(text)){
            faxText.setForeground(Color.BLACK);
        } else {
            faxText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_faxTextCaretUpdate

    private void emailTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_emailTextCaretUpdate
        String text = emailText.getText();
        if (emailCheck(text)){
            emailText.setForeground(Color.BLACK);
        } else {
            emailText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_emailTextCaretUpdate

    private void localidadTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_localidadTextCaretUpdate
        String text = localidadText.getText();
        if (nameCheck(text)){
            localidadText.setForeground(Color.BLACK);
        } else {
            localidadText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_localidadTextCaretUpdate

    private void niflTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_niflTextCaretUpdate
        String text = niflText.getText();
        if (text.matches("[a-zA-Z]") && comprobarDNI()){
            niflText.setForeground(Color.BLACK);
        } else {
            niflText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_niflTextCaretUpdate

    private void niflTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_niflTextFocusLost
        String text = niflText.getText();
        if (text.matches("[a-zA-Z]") && comprobarDNI()){
            niflText.setForeground(Color.BLACK);
        } else {
            niflText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_niflTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario().setVisible(true));
    }
    
    //método para comprobar Nombre y Apellido
    public static boolean nameCheck(String text){
        return text.matches("[A-Za-z\\s]+"); 
    }
    
    //método para comprobar Teléfono, Móvil, Fax
    public static boolean phoneCheck(String text){
        return text.matches("[0-9]{9}");
    }
    
    //método para comprobar email
    public static boolean emailCheck(String text){
        return text.matches("^\\S+@\\S+\\.\\S+$");
    }
    
    //metodo para código
    public static boolean codigoCheck(String text){
        return text.matches("[0-9]{5}");
    }
    
    //metodo para comprobar codigo postal
    public static boolean cpCheck(String text){
        return text.matches("[0-9]{5}");
    }
    
    //metodo para comprobar DNIN
    public static boolean numCheck(String text){
        return text.matches("[0-9]{8}");
    }
    
    //método para comprobar DNIl
    public static boolean letraCheck(String text){
        return text.matches("[A-Za-z]");
    }
    
    public boolean comprobarDNI(){
        String num = nifnText.getText();
        String let = niflText.getText();
        
        String[] letras = {"T", "R", "W", "A", "G", "M", "Y", "F", "P", "D", "X","B", 
                           "N", "J", "Z", "S", "Q", "V", "H", "L", "C", "K", "E"};
        int resto1 = Integer.parseInt(num) % 23;
        if (let.toUpperCase().equals(letras[resto1])){
            return true;
        } else {
        return false;
            }
        
    }
    
    public void reset(){
        codigoText.grabFocus();
        codigoText.setText("");
        nifnText.setText("");
        niflText.setText("");
        nombreText.setText("");
        apellidosText.setText("");
        domicilioText.setText("");
        cpText.setText("");
        localidadText.setText("");
        telefonoText.setText("");
        movilText.setText("");
        faxText.setText("");
        emailText.setText("");
        totalText.setText("");
        
    }
    public static void showOtherWindow(){
        
    }
    
    
    
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosText;
    private javax.swing.JTextField codigoText;
    private javax.swing.JTextField cpText;
    private javax.swing.JTextField domicilioText;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField faxText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField localidadText;
    private javax.swing.JTextField movilText;
    private javax.swing.JTextField niflText;
    private javax.swing.JTextField nifnText;
    private javax.swing.JTextField nombreText;
    private javax.swing.JTextField telefonoText;
    private javax.swing.JTextField totalText;
    // End of variables declaration//GEN-END:variables
}
