/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.josefeyjoo.almacen.view.ui;

import com.josefeyjoo.almacen.model.entity.Cliente;
import com.josefeyjoo.almacen.view.*;
import com.josefeyjoo.almacen.view.AppNav;
import com.josefeyjoo.almacen.view.MODO;
import com.josefeyjoo.almacen.viewmodel.ViewModel;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author jfeyj
 */
public class ClienteFormulario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteFormulario.class.getName());
    private ViewModel vm;
    private MODO modo = MODO.NULO;
    /**
     * Creates new form Formulario
     */
    public ClienteFormulario(ViewModel vm) {
        this.vm = vm;
        initComponents();
        showCurrentMode();
        codigoText.setEnabled(false);
        enableFields(false);
    }
    
    public void showCurrentMode(){
        jTextCurMode.setText(this.modo.toString());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jMenuItem1 = new javax.swing.JMenuItem();
        codigoText = new javax.swing.JTextField();
        nifnText = new javax.swing.JTextField();
        nombreText = new javax.swing.JTextField();
        apellidosText = new javax.swing.JTextField();
        domicilioText = new javax.swing.JTextField();
        cpText = new javax.swing.JTextField();
        localidadText = new javax.swing.JTextField();
        telefonoText = new javax.swing.JTextField();
        movilText = new javax.swing.JTextField();
        faxText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        totalText = new javax.swing.JTextField();
        niflText = new javax.swing.JTextField();
        jButAce = new javax.swing.JButton();
        jButCan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButSal = new javax.swing.JButton();
        jTextCurMode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMan = new javax.swing.JMenu();
        jMenuManAlt = new javax.swing.JMenuItem();
        jMenuManBaj = new javax.swing.JMenuItem();
        jMenuManMod = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuManVol = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuPorCodigo = new javax.swing.JMenu();
        jMenuConCod = new javax.swing.JMenuItem();
        jMenuConEnt = new javax.swing.JMenuItem();
        jMenuCodGra = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Prueba de entrada de datos");

        codigoText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                codigoTextCaretUpdate(evt);
            }
        });
        codigoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextActionPerformed(evt);
            }
        });

        nifnText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nifnTextCaretUpdate(evt);
            }
        });
        nifnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nifnTextActionPerformed(evt);
            }
        });

        nombreText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nombreTextCaretUpdate(evt);
            }
        });
        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });

        apellidosText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                apellidosTextCaretUpdate(evt);
            }
        });
        apellidosText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosTextActionPerformed(evt);
            }
        });

        domicilioText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                domicilioTextCaretUpdate(evt);
            }
        });
        domicilioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domicilioTextActionPerformed(evt);
            }
        });

        cpText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                cpTextCaretUpdate(evt);
            }
        });
        cpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpTextActionPerformed(evt);
            }
        });

        localidadText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                localidadTextCaretUpdate(evt);
            }
        });
        localidadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidadTextActionPerformed(evt);
            }
        });

        telefonoText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                telefonoTextCaretUpdate(evt);
            }
        });
        telefonoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTextActionPerformed(evt);
            }
        });

        movilText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                movilTextCaretUpdate(evt);
            }
        });
        movilText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movilTextActionPerformed(evt);
            }
        });

        faxText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                faxTextCaretUpdate(evt);
            }
        });
        faxText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxTextActionPerformed(evt);
            }
        });

        emailText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                emailTextCaretUpdate(evt);
            }
        });
        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });

        totalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTextActionPerformed(evt);
            }
        });

        niflText.setEnabled(false);
        niflText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                niflTextCaretUpdate(evt);
            }
        });
        niflText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                niflTextFocusLost(evt);
            }
        });
        niflText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niflTextActionPerformed(evt);
            }
        });

        jButAce.setText("Aceptar");
        jButAce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAceActionPerformed(evt);
            }
        });

        jButCan.setText("Cancelar");
        jButCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCanActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("N.I.F");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellidos");

        jLabel5.setText("Domicilio");

        jLabel6.setText("Codigo Postal");

        jLabel7.setText("Localidad");

        jLabel8.setText("Teléfono");

        jLabel9.setText("Móvil");

        jLabel10.setText("Fax");

        jLabel11.setText("Email");

        jLabel12.setText("Total Ventas");

        jButSal.setText("Salir");
        jButSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalActionPerformed(evt);
            }
        });

        jTextCurMode.setEditable(false);
        jTextCurMode.setToolTipText("");

        jLabel13.setText("Modo Actual");

        jMenuMan.setText("Mantenimiento");

        jMenuManAlt.setText("Alta");
        jMenuManAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManAltActionPerformed(evt);
            }
        });
        jMenuMan.add(jMenuManAlt);

        jMenuManBaj.setText("Baja");
        jMenuManBaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManBajActionPerformed(evt);
            }
        });
        jMenuMan.add(jMenuManBaj);

        jMenuManMod.setText("Modificaciones");
        jMenuManMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManModActionPerformed(evt);
            }
        });
        jMenuMan.add(jMenuManMod);
        jMenuMan.add(jSeparator1);

        jMenuManVol.setText("Volver");
        jMenuManVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManVolActionPerformed(evt);
            }
        });
        jMenuMan.add(jMenuManVol);

        jMenuBar1.add(jMenuMan);

        jMenu2.setText("Consultas");

        jMenuPorCodigo.setText("Por Código");

        jMenuConCod.setText("Por Código");
        jMenuConCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConCodActionPerformed(evt);
            }
        });
        jMenuPorCodigo.add(jMenuConCod);

        jMenuConEnt.setText("Entre Códigos");
        jMenuPorCodigo.add(jMenuConEnt);

        jMenuCodGra.setText("Gráficos");
        jMenuPorCodigo.add(jMenuCodGra);

        jMenu2.add(jMenuPorCodigo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(domicilioText, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosText, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(localidadText, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(movilText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(faxText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nifnText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(niflText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addContainerGap(76, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButAce)
                                .addGap(18, 18, 18)
                                .addComponent(jButCan)
                                .addGap(18, 18, 18)
                                .addComponent(jButSal)
                                .addGap(75, 75, 75))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jTextCurMode, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCurMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nifnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(niflText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(apellidosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(domicilioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localidadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movilText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButAce)
                    .addComponent(jButCan)
                    .addComponent(jButSal))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codigoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextActionPerformed

    }//GEN-LAST:event_codigoTextActionPerformed

    private void nifnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nifnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nifnTextActionPerformed

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextActionPerformed

    private void apellidosTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosTextActionPerformed

    private void domicilioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domicilioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domicilioTextActionPerformed

    private void cpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpTextActionPerformed

    private void localidadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidadTextActionPerformed

    private void telefonoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTextActionPerformed

    private void movilTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movilTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movilTextActionPerformed

    private void faxTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faxTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faxTextActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void totalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTextActionPerformed

    private void niflTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niflTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niflTextActionPerformed

    private void jButCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCanActionPerformed
        // TODO add your handling code here:
        reset();
        enableFields(false);
        codigoText.setEnabled(true);
    }//GEN-LAST:event_jButCanActionPerformed

    private void jButAceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAceActionPerformed
        String codigo = codigoText.getText();
        switch(this.modo){
            case (MODO.NULO):
                break;

            case (MODO.ALTA):
                if ((codigoCheck(codigo)) && vm.getCodigo()==null) {
                    try {
                        vm.setCodigo(codigo);
                        if (vm.consultaCliente() == null){
                            enableFields(true);
                        };
                        //Mostrar modal aqui
                    } catch (SQLException ex) {
                        enableFields(true);
                    }
                } else if(vm.getCodigo()!=null) {
                    try {
                        Cliente uiCliente = crearClienteUI();
                        vm.setUiCliente(uiCliente);
                        vm.crearCliente();
                        vm.setCodigo(null);
                        vm.setUiCliente(null);
                        reset();
                    } catch (SQLException ex) {
                        System.getLogger(ClienteFormulario.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }
                break;

            case (MODO.BAJA):             
                if (codigoCheck(codigo)){
                try {
                    vm.setCodigo(codigo);
                    if (vm.consultaCliente()!=null){
                        vm.deleteCliente();
                        vm.setCodigo(null);
                    } else {
                        System.out.println("Error");
                        }
                } catch (SQLException ex) {
                    System.getLogger(ClienteFormulario.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            }
                break;

            case (MODO.CONSULTA):
                if ((codigoCheck(codigo))&& vm.getCodigo()==null){
                    vm.setCodigo(codigo);
                    try {
                        Cliente ui;
                        ui = vm.consultaCliente();
                        mostrarClienteUI(ui);
                        vm.setCodigo(null);
                    } catch (SQLException ex) {
                        System.getLogger(ClienteFormulario.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }
                break;

            case (MODO.MODIFICACION):
                break;

            
        }
        
    }//GEN-LAST:event_jButAceActionPerformed

    private void codigoTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_codigoTextCaretUpdate
        String text = codigoText.getText();
        if (codigoCheck(text)){
            codigoText.setForeground(Color.BLACK);
        } else {
            codigoText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_codigoTextCaretUpdate

    private void nifnTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nifnTextCaretUpdate
        String text = nifnText.getText();
        if (numCheck(text)){
            letraDNI();
            nifnText.setForeground(Color.BLACK);
        } else {
            niflText.setText("");
            nifnText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_nifnTextCaretUpdate

    private void nombreTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nombreTextCaretUpdate
        String text = nombreText.getText();
        if (stringCheck(text,15)){
            nombreText.setForeground(Color.BLACK);
        } else {
            nombreText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_nombreTextCaretUpdate

    private void apellidosTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_apellidosTextCaretUpdate
        String text = apellidosText.getText();
        if (stringCheck(text, 35)){
            apellidosText.setForeground(Color.BLACK);
        } else {
            apellidosText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_apellidosTextCaretUpdate

    private void cpTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_cpTextCaretUpdate
        String text = cpText.getText();
        if (cpCheck(text)){
            cpText.setForeground(Color.BLACK);
        } else {
            cpText.setForeground(Color.RED);
        } 
    }//GEN-LAST:event_cpTextCaretUpdate

    private void telefonoTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_telefonoTextCaretUpdate
        String text = telefonoText.getText();
        if (phoneCheck(text)){
            telefonoText.setForeground(Color.BLACK);
        } else {
            telefonoText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_telefonoTextCaretUpdate

    private void movilTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_movilTextCaretUpdate
        String text = movilText.getText();
        if (phoneCheck(text)){
            movilText.setForeground(Color.BLACK);
        } else {
            movilText.setForeground(Color.RED);
        } 
    }//GEN-LAST:event_movilTextCaretUpdate

    private void faxTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_faxTextCaretUpdate
        String text = faxText.getText();
        if (phoneCheck(text)){
            faxText.setForeground(Color.BLACK);
        } else {
            faxText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_faxTextCaretUpdate

    private void emailTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_emailTextCaretUpdate
        String text = emailText.getText();
        if (emailCheck(text)){
            emailText.setForeground(Color.BLACK);
        } else {
            emailText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_emailTextCaretUpdate

    private void localidadTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_localidadTextCaretUpdate
        String text = localidadText.getText();
        if (stringCheck(text, 20)){
            localidadText.setForeground(Color.BLACK);
        } else {
            localidadText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_localidadTextCaretUpdate

    private void niflTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_niflTextCaretUpdate
        String text = niflText.getText();
        if (text.matches("[a-zA-Z]") ){
            niflText.setForeground(Color.BLACK);
        } else {
            niflText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_niflTextCaretUpdate

    private void niflTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_niflTextFocusLost
        String text = niflText.getText();
        if (text.matches("[a-zA-Z]")){
            niflText.setForeground(Color.BLACK);
        } else {
            niflText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_niflTextFocusLost

    private void jButSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalActionPerformed
        changeMode(MODO.NULO);
    }//GEN-LAST:event_jButSalActionPerformed

    private void jMenuManVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManVolActionPerformed
       AppNav.navigate(this, "HOME");
    }//GEN-LAST:event_jMenuManVolActionPerformed

    private void jMenuManAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManAltActionPerformed
        changeMode(MODO.ALTA);
    }//GEN-LAST:event_jMenuManAltActionPerformed

    private void jMenuManModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManModActionPerformed
        changeMode(MODO.MODIFICACION);
    }//GEN-LAST:event_jMenuManModActionPerformed

    private void jMenuManBajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManBajActionPerformed
        changeMode(MODO.BAJA);
    }//GEN-LAST:event_jMenuManBajActionPerformed

    private void jMenuConCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConCodActionPerformed
        changeMode(MODO.CONSULTA);
    }//GEN-LAST:event_jMenuConCodActionPerformed

    private void domicilioTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_domicilioTextCaretUpdate
        String text = domicilioText.getText();
        if (domicilioCheck(text)){
            domicilioText.setForeground(Color.BLACK);
        } else {
           domicilioText.setForeground(Color.RED);
        } 
    }//GEN-LAST:event_domicilioTextCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new FormularioTemplate().setVisible(true));
    }
    
    //método para comprobar Nombre, Apellido y Localidad
    public static boolean stringCheck(String text, int stringLength){
        
        return text.matches("[A-Za-z\\s]{1,"+ stringLength +"}"); 
    }
    
    //método para comprobar Teléfono, Móvil, Fax
    public static boolean phoneCheck(String text){
        if (text.isBlank()){
            return true;
        } else {
            return text.matches("[0-9]{9}");
        }
        
    }
    
    //método para comprobar email
    public static boolean emailCheck(String text){
        if (text.isBlank()){
            return true;
        } else {
            return text.matches("^\\S+@\\S+\\.\\S+$");
        }
        
    }
    
    //metodo para código
    public static boolean codigoCheck(String text){
        return text.matches("[0-9]{5}");
    }
    
    //metodo para comprobar codigo postal
    public static boolean cpCheck(String text){
        return text.matches("[0-9]{5}");
    }
    
    //metodo para comprobar DNIN
    public static boolean numCheck(String text){
        return text.matches("[0-9]{8}");
    }
    
    //metodo para comprobar la longitud de domicilio
    public static boolean domicilioCheck(String text){
        return text.matches("^.{1,40}$");
    }
    
    public void letraDNI(){
        String num = nifnText.getText();
        String[] letras = {"T", "R", "W", "A", "G", "M", "Y", "F", "P", "D", "X","B", 
                           "N", "J", "Z", "S", "Q", "V", "H", "L", "C", "K", "E"};
        int resto1 = Integer.parseInt(num) % 23;
        if (numCheck(nifnText.getText())){
            niflText.setText(letras[resto1]);
        }
    } 
    
    public void reset(){
        codigoText.grabFocus();
        codigoText.setText("");
        nifnText.setText("");
        niflText.setText("");
        nombreText.setText("");
        apellidosText.setText("");
        domicilioText.setText("");
        cpText.setText("");
        localidadText.setText("");
        telefonoText.setText("");
        movilText.setText("");
        faxText.setText("");
        emailText.setText("");
        totalText.setText("");
    }
    
    public void enableFields(boolean active){
        nifnText.setEnabled(active);
        nombreText.setEnabled(active);
        apellidosText.setEnabled(active);
        domicilioText.setEnabled(active);
        cpText.setEnabled(active);
        localidadText.setEnabled(active);
        telefonoText.setEnabled(active);
        movilText.setEnabled(active);
        faxText.setEnabled(active);
        emailText.setEnabled(active);
        totalText.setEnabled(active);
    }
    
    public void changeMode(MODO mode){
        reset();
        this.modo = mode;
        showCurrentMode();
        enableFields(false);
        vm.setCodigo(null);
        if (mode==MODO.NULO){
            codigoText.setEnabled(false);
        } else {
            codigoText.setEnabled(true);
        }
    }
    public boolean comprobarCampos(){
        if (numCheck(nifnText.getText())){
            if (stringCheck(nombreText.getText(),15)){
                if (stringCheck(apellidosText.getText(),35)){
                    if (domicilioCheck(domicilioText.getText())){
                        if (cpCheck(cpText.getText())){
                            if (stringCheck(localidadText.getText(),20)){
                                if (phoneCheck(telefonoText.getText())){
                                    if (phoneCheck(movilText.getText())){
                                        if (phoneCheck(faxText.getText())){
                                            if (emailCheck(emailText.getText())){
                                                return true;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        
        return false;
    }
    
    public Cliente crearClienteUI(){
        float totalVentas;
        String ventasString = totalText.getText();
        if (ventasString.isEmpty()){
            totalVentas = 0;
        } else {
            totalVentas = Float.valueOf(ventasString);
        }
        Cliente cli = new Cliente();
        cli.setCodigo(codigoText.getText());
        cli.setNif(nifnText.getText()+niflText.getText());
        cli.setApellidos(apellidosText.getText());
        cli.setNombre(nombreText.getText());
        cli.setDomicilio(domicilioText.getText());
        cli.setCodigoPostal(cpText.getText());
        cli.setLocalidad(localidadText.getText());
        cli.setTelefono(telefonoText.getText());
        cli.setMovil(movilText.getText());
        cli.setFax(faxText.getText());
        cli.setEmail(emailText.getText());
        cli.setTotalVentas(totalVentas);
        
        return cli;
    }
    
    public void mostrarClienteUI(Cliente cli){
        String numeroDNI = cli.getNif().substring(0, 8);
        codigoText.setText(cli.getCodigo());
        nifnText.setText(numeroDNI);
        letraDNI();
        apellidosText.setText(cli.getApellidos());
        nombreText.setText(cli.getNombre());
        domicilioText.setText(cli.getDomicilio());
        cpText.setText(cli.getCodigoPostal());
        localidadText.setText(cli.getLocalidad());
        telefonoText.setText(cli.getTelefono());
        movilText.setText(cli.getMovil());
        faxText.setText(cli.getFax());
        emailText.setText(cli.getEmail());
        totalText.setText(String.valueOf(cli.getTotalVentas()));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosText;
    private javax.swing.JTextField codigoText;
    private javax.swing.JTextField cpText;
    private javax.swing.JTextField domicilioText;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField faxText;
    private javax.swing.JButton jButAce;
    private javax.swing.JButton jButCan;
    private javax.swing.JButton jButSal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCodGra;
    private javax.swing.JMenuItem jMenuConCod;
    private javax.swing.JMenuItem jMenuConEnt;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuMan;
    private javax.swing.JMenuItem jMenuManAlt;
    private javax.swing.JMenuItem jMenuManBaj;
    private javax.swing.JMenuItem jMenuManMod;
    private javax.swing.JMenuItem jMenuManVol;
    private javax.swing.JMenu jMenuPorCodigo;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextCurMode;
    private javax.swing.JTextField localidadText;
    private javax.swing.JTextField movilText;
    private javax.swing.JTextField niflText;
    private javax.swing.JTextField nifnText;
    private javax.swing.JTextField nombreText;
    private javax.swing.JTextField telefonoText;
    private javax.swing.JTextField totalText;
    // End of variables declaration//GEN-END:variables
}
